### ISSUE TITLE
[Error]: 'google-place-autocomplete' is not a known element

### ISSUE THREAD

**Issue by Pazitos10** [souzadriano/ionic2-google-places-autocomplete#2]
Hi again! when trying to use this module and run ionic either with serve or run options I get this error message:

![bug_ionic](https://user-images.githubusercontent.com/5199304/29125961-7b3228ee-7cf3-11e7-848c-561d19ff8467.png)

And it's caused due to a typo in README.md, so when it says:

```html
<google-place-autocomplete (callback)="detail($event[0])" key="GOOGLE_PLACES_API_KEY"></google-place-autocomplete>
 ```

It should be:
```html
<google-places-autocomplete (callback)="detail($event[0])" key="GOOGLE_PLACES_API_KEY"></google-places-autocomplete>
 ```
That is so because according to the source code (in the dist files):
```js
...
GooglePlacesAutocompleteComponent.decorators = [
        { type: Component, args: [{
                    selector: 'google-places-autocomplete',
...
```
Notice that the selector name is ```'google-places-autocomplete'``` instead of ``` 'google-place-autocomplete'```

So, fixing README.md should do the trick :)

Cheers!
P.S.: Sorry this is too verbose.

**Comment by souzadriano** [comment]
Thank you again @Pazitos10 , I update README and npm repository.
