### ISSUE TITLE
<google-place-autocomplete (callback)="detail($event[0])" key="GOOGLE_PLACES_API_KEY"></google-place-autocomplete>

### ISSUE THREAD

**Issue by alvinchettiar** [souzadriano/ionic2-google-places-autocomplete#3]
Element not found error.
The correct syntax is 'google-places-autocomplete'

<google-places-autocomplete (callback)="detail($event[0])" key="GOOGLE_PLACES_API_KEY"></google-places-autocomplete>

**Comment by souzadriano** [comment]
Thank you @alvinchettiar, I update README and npm repository.
