### ISSUE TITLE
The Angular AoT build failed

### ISSUE THREAD

**Issue by rahulrajpal2911** [souzadriano/ionic2-google-places-autocomplete#7]
**I'm trying to production build my ionic app but I'm getting the below error, please guide me as I'm new in typescript.
Thanks in advance and sorry for my bad English.**

ionic cordova build android --prod
Running app-scripts build: --prod --platform android --target cordova
[15:29:46]  build prod started ...
[15:29:46]  clean started ...
[15:29:46]  clean finished in 32 ms
[15:29:46]  copy started ...
[15:29:47]  deeplinks started ...
[15:29:47]  deeplinks finished in 311 ms
[15:29:47]  ngc started ...
[15:30:02]  typescript error
            ("er="Enter your address" [(ngModel)]="search" (keyup)="geolocate(search)" type="text"></ion-input> [ERROR
            ->]<google-places-autocomplete (callback)="detail($event[0])" types="establishment" location="23.2599, 7")

Error: The Angular AoT build failed. See the issues above
    at C:\Users\RAHUL-RAJPAL\Apps\TJKN-Customer\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:237:55
    at step (C:\Users\RAHUL-RAJPAL\Apps\TJKN-Customer\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:32:23)
    at Object.next (C:\Users\RAHUL-RAJPAL\Apps\TJKN-Customer\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:13:53)
    at fulfilled (C:\Users\RAHUL-RAJPAL\Apps\TJKN-Customer\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:4:58)
    at <anonymous>
[15:30:02]  copy finished in 15.48 s

**Comment by souzadriano** [comment]
Hi @rahulrajpal2911 ,

What Ionic version of you app?

Can you give more parts of code of the html, controller and module?

**Comment by rahulrajpal2911** [comment]
Hi @souzadriano ,

Below is my html code:
<ion-content padding>
  <google-places-autocomplete (callback)="detail($event[0])" types="establishment" location="23.2599, 77.4126" radius="20000" strictbounds key="I mentioned it in project"></google-places-autocomplete>
  <ion-card>
    <ion-card-content>
      <form (submit)="addAddress(form)">
        <ion-input type="hidden" [(ngModel)]="form.id" name="id"></ion-input>
        <ion-input type="hidden" [(ngModel)]="form.latitude" name="latitude"></ion-input>
        <ion-input type="hidden" [(ngModel)]="form.longitude" name="longitude"></ion-input>
        <ion-input type="hidden" [(ngModel)]="form.full_address" name="full_address"></ion-input>
        <ion-list>
          <ion-item>
            <ion-label floating>Flat / Building Name</ion-label>
            <ion-input type="text" [(ngModel)]="form.street" name="street"></ion-input>
          </ion-item>

          <ion-item>
            <ion-label floating>Landmark</ion-label>
            <ion-input type="text" [(ngModel)]="form.route" name="route"></ion-input>
          </ion-item>

          <ion-item>
            <ion-label floating>Area</ion-label>
            <ion-input type="text" [(ngModel)]="form.area" name="area"></ion-input>
          </ion-item>

          <ion-item>
            <ion-label floating>Pincode</ion-label>
            <ion-input type="text" [(ngModel)]="form.postal_code" name="postal_code"></ion-input>
          </ion-item>
          <ion-item>
            <ion-label floating>City</ion-label>
            <ion-input type="text" readonly [(ngModel)]="form.city" name="city"></ion-input>
          </ion-item>

          <ion-item>
            <ion-label floating>State</ion-label>
            <ion-input type="text" readonly [(ngModel)]="form.state" name="state"></ion-input>
          </ion-item>

          <ion-item>
            <ion-label floating>Country</ion-label>
            <ion-input type="text" readonly [(ngModel)]="form.country" name="country"></ion-input>
          </ion-item>
          <ion-item>
            <button type="submit" ion-button block>Save</button>
          </ion-item>

        </ion-list>
      </form>
    </ion-card-content>
  </ion-card>
  <ion-fab top right edge>
    <button ion-fab mini color="dark" *ngIf="form.id > 0" (click)="delete_address(form.id)">
      <ion-icon name="trash"></ion-icon>
    </button>
  </ion-fab>
</ion-content>

-------------------------------------------------------------------------------------------------------------

Below are the dependencies and version in package.json

  "dependencies": {
    "[at]angular/common": "5.0.1",
    "[at]angular/compiler": "5.0.1",
    "[at]angular/compiler-cli": "5.0.1",
    "[at]angular/core": "5.0.1",
    "[at]angular/forms": "5.0.1",
    "[at]angular/http": "5.0.1",
    "[at]angular/platform-browser": "5.0.1",
    "[at]angular/platform-browser-dynamic": "5.0.1",
    "[at]ionic-native/action-sheet": "4.5.3",
    "[at]ionic-native/call-number": "4.5.3",
    "[at]ionic-native/core": "4.5.3",
    "[at]ionic-native/date-picker": "4.5.3",
    "[at]ionic-native/diagnostic": "4.5.3",
    "[at]ionic-native/facebook": "4.5.3",
    "[at]ionic-native/geolocation": "4.5.3",
    "[at]ionic-native/google-plus": "4.5.3",
    "[at]ionic-native/http": "4.5.3",
    "[at]ionic-native/in-app-browser": "4.5.3",
    "[at]ionic-native/location-accuracy": "4.5.3",
    "[at]ionic-native/native-geocoder": "4.5.3",
    "[at]ionic-native/social-sharing": "4.5.3",
    "[at]ionic-native/splash-screen": "4.5.3",
    "[at]ionic-native/status-bar": "4.5.3",
    "[at]ionic-native/toast": "4.5.3",
    "[at]ionic/pro": "1.0.16",
    "[at]ionic/storage": "^2.1.3",
    "call-number": "^1.0.1",
    "cordova-android": "6.3.0",
    "cordova-plugin-actionsheet": "^2.3.3",
    "cordova-plugin-advanced-http": "^1.10.0",
    "cordova-plugin-datepicker": "^0.9.3",
    "cordova-plugin-device": "^1.1.7",
    "cordova-plugin-facebook4": "^1.9.1",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-geolocation": "^3.0.0",
    "cordova-plugin-googleplus": "^5.2.1",
    "cordova-plugin-inappbrowser": "^1.7.2",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-nativegeocoder": "^2.0.5",
    "cordova-plugin-request-location-accuracy": "^2.2.2",
    "cordova-plugin-splashscreen": "^4.1.0",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "^5.2.1",
    "cordova-plugin-x-toast": "^2.6.0",
    "cordova-sqlite-storage": "^2.2.0",
    "cordova.plugins.diagnostic": "^3.9.2",
    "es6-promise-plugin": "^4.1.0",
    "ionic-angular": "3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionic2-google-places-autocomplete": "^1.0.2",
    "ionicons": "3.0.0",
    "moment": "^2.20.1",
    "mx.ferreyra.callnumber": "0.0.2",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.8",
    "typescript": "2.4.2"
  },
    "platforms": [
      "android"
    ]

Note: I replaced "@" sign with "[at]" here because "@" is not working here.

Its working fine when using "ionic serve" and "ionic cordova build android" commands..

**Comment by souzadriano** [comment]
Hi @rahulrajpal2911,

In my tests it's working.

I attach my test project below.

[myPlaces5.zip](https://github.com/souzadriano/ionic2-google-places-autocomplete/files/1745013/myPlaces5.zip)

Use git diff to view the modifications.
